---
- name: Build server configuration
  hosts: build
  become: yes

  roles:
   - initpackages
   - build

- name: Deploy server configuration
  hosts: deploy
  become: yes

  roles:
   - initpackages
   - file
   - deploy

