---
# tasks file for initpackages
- name: Install packages BUILD
  apt: name={{item}} state=present
  with_items:
    - rsync
    - maven
    - git
  when: state == "Build"

- name: Install packages DEPLOY
  apt: name={{item}} state=present
  with_items:
    - rsync
    - tomcat9
  when: state == "Deploy"