---
# tasks file for file

- name: Copy File War from Stage to Web (synchronize)
  synchronize:
    src: /home/samplejavacode/target/addressbook.war
    dest: /var/lib/tomcat9/webapps/addressbook.war
  delegate_to: "{{ ip_build }}"

#- name: Copy File War from BUILD to MASTER
#  fetch:
#    src: /home/samplejavacode/target/addressbook.war
#    dest: ./
#    flat: yes
#  when: state == "Build"  

#- name: Copy the file from MASTER to DEPLOY
#  copy:
#    src: ./addressbook.war
#    dest: /var/lib/tomcat9/webapps
#  when: state == "Deploy"