---
# tasks file for file
- name: Copy File War from BUILD to MASTER
  fetch:
    src: /home/samplejavacode/target/addressbook.war
    dest: ./
    flat: yes
  when: state == "Build"  

- name: Copy the file from MASTER to DEPLOY
  copy:
    src: ./addressbook.war
    dest: /var/lib/tomcat9/webapps
  when: state == "Deploy"